[package]
name = "nimiq-jsonrpc-client"
version = "0.1.0"
authors = ["Janosch Gräf <janosch@nimiq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
log = "0.4"
thiserror = "1.0"
async-trait = "0.1"
reqwest = { version = "0.10", optional = true, features = ["json"] }
tokio-tungstenite = { version = "0.11", optional = true }
tungstenite = { version = "0.11", optional = true }
tokio = { version = "0.2", features = ["net", "sync"], optional = true }
url = "2.1.1"
serde_json = "1.0"
futures = "0.3"
nimiq-jsonrpc-core = { path = "../nimiq-jsonrpc-core" }

[features]
default = ["http", "websocket"]
http = ["reqwest"]
websocket = ["tokio-tungstenite", "tokio", "tungstenite"]
